services:
  web:
      container_name: dash_app
      build: .
      env_file:
        - .env
      ports:
        - "5000:5000"
      depends_on:
        - db
      volumes:
        - .:/app
      restart: on-failure
  db:
      image: postgres:17.4
      env_file:
        - .env
      ports:
        - "5002:5432"
      volumes:
        - weather-db:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
volumes:
  weather-db:
